Cleanup the caenvmelib dockerfile

diff --git a/Dockerfile.caen-mdpp16 b/Dockerfile.caen-mdpp16
--- a/Dockerfile.caen-mdpp16
+++ b/Dockerfile.caen-mdpp16
@@ -1,13 +1,23 @@
 # syntax=docker/dockerfile:1.5
 # vim:ft=dockerfile
 
+# Based on info from https://fy.chalmers.se/subatom/subexp-daq/ and
+# https://fy.chalmers.se/subatom/subexp-daq/minidaq_v2718_mdpp16.txt
+#
 # To build:
-#   Place the extracted CAENVMELib-v4.0.2  in external/
+#   Place the extracted CAENVMELib in external/
 #   git submodule update --init --recursive
-#   docker build -t chalmers.se-mvlc:latest --progress plain .
+#   docker build -f Dockerfile.caen-mdpp16 -t chalmers.se-caen-mdpp16:latest --progress plain .
 
 FROM debian:stable as build
 
+ARG MAKEJOBS=8
+ARG CAENVERSION="v4.0.2"
+ENV CAENLIB_BASE="CAENVMELib-${CAENVERSION}"
+ENV CAENLIB_DIR="/sources/${CAENLIB_BASE}"
+ENV CAENLIB_SO="$CAENLIB_DIR/lib/x64/libCAENVME.so.$CAENVERSION"
+ENV CPPFLAGS="-I$CAENLIB_DIR/include"
+ENV LIBS=${CAENLIB_SO}
 ENV DEBIAN_FRONTEND="noninteractive"
 ENV TZ="Etc/UTC"
 
@@ -23,16 +33,11 @@ RUN echo "set nocompatible\nset bg=dark\nsyntax enable\n" >> ~/.vimrc
 COPY . /sources/
 WORKDIR /sources
 
-ARG MAKEJOBS=8
-ARG CAENVERSION="v4.0.2"
-ENV CAENLIB_DIR="/sources/CAENVMELib-${CAENVERSION}"
-ENV CAENLIB_SO="$CAENLIB_DIR/lib/x64/libCAENVME.so.$CAENVERSION"
-ENV CPPFLAGS="-I$CAENLIB_DIR/include"
-ENV LIBS=${CAENLIB_SO}
+RUN test -d external/$CAENLIB_BASE || (echo "CAENVMELib is missing"; exit 1)
 
 # Create symlinks to libs in /sources. Having another subdir in-between did
 # break the build.
-RUN ln -s external/CAENVMELib-v4.0.2
+RUN ln -s external/$CAENLIB_BASE
 RUN ln -s external/drasi
 RUN ln -s external/nurdlib
 RUN ln -s external/ucesb
@@ -42,11 +47,11 @@ RUN ln -s external/ucesb
 # this flag. Note: also removes -ansi as the whole line is deleted.
 RUN sed -i -e '/pedantic-errors/d' nurdlib/Makefile
 
-RUN make -j${MAKEJOBS} -C drasi
-RUN make -j${MAKEJOBS} -C drasi showconfig showconfig_all
-RUN make -j${MAKEJOBS} -C nurdlib fuser_drasi
-RUN make -j${MAKEJOBS} -C nurdlib showconfig
-RUN make -j${MAKEJOBS} -C ucesb empty
+RUN make -j$MAKEJOBS -C drasi
+RUN make -j$MAKEJOBS -C drasi showconfig showconfig_all
+RUN make -j$MAKEJOBS -C nurdlib fuser_drasi
+RUN make -j$MAKEJOBS -C nurdlib showconfig
+RUN make -j$MAKEJOBS -C ucesb empty
 
 WORKDIR /sources/scripts
 RUN  curl -O https://fy.chalmers.se/subatom/subexp-daq/minidaq_v2718_mdpp16/main.cfg
